"""Lesson router."""

from __future__ import annotations

from fastapi import APIRouter, Depends, Header
from sqlalchemy.ext.asyncio import AsyncSession
from typing import Optional

from app.database import get_session
from app.dependencies import get_current_user
from app.exceptions import AppException
from app.models.user import User
from app.schemas.lesson import DeclineWordRequest, DeclineWordResponse
from app.schemas.lesson_evaluate import (
    EvaluateRequest,
    EvaluateResponse,
    ExerciseInfoResponse,
    ExerciseResultResponse,
    ReportRequest,
    ReportResponse,
    SuggestionActionRequest,
    SuggestionActionResponse,
)
from app.schemas.lesson_resume import (
    AbandonResponse,
    CurrentExerciseResponse,
    LessonSummaryResponse,
)
from app.schemas.lesson_start import LessonStartRequest, LessonStartResponse
from app.services.lesson_exercise_service import LessonExerciseService
from app.services.lesson_preview_service import LessonPreviewService
from app.services.lesson_resume_service import LessonResumeService
from app.services.lesson_start_service import LessonStartService
from app.services.lesson_summary_service import LessonSummaryService
from app.services.suggestion_service import SuggestionService
from app.services.report_service import ReportService

router = APIRouter(prefix="/lesson", tags=["lesson"])


@router.post("/preview")
async def preview_lesson(
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session),
):
    """
    Preview lesson word selection without creating anything.
    
    Returns state based on current conditions:
    - resume: if there's an in-progress lesson
    - limit_reached: if daily limit is reached
    - ready: if lesson can be started
    - no_words: if no words are available
    """
    # Check onboarding
    if not current_user.is_onboarded:
        raise AppException(
            status_code=409,
            code="onboarding_required",
            message="Требуется завершение онбординга"
        )

    service = LessonPreviewService(session, current_user)
    return await service.preview()


@router.post("/start", response_model=LessonStartResponse)
async def start_lesson(
    request: LessonStartRequest,
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session),
    idempotency_key: Optional[str] = Header(None, alias="Idempotency-Key"),
):
    """
    Start a new lesson with LLM-generated sentences.
    
    Creates lesson with exercises containing sentences generated by LLM.
    Uses advisory lock to prevent parallel starts.
    """
    service = LessonStartService(session, current_user)
    return await service.start_lesson(
        word_ids=request.word_ids,
        idempotency_key=idempotency_key,
    )


@router.post("/new-word/decline", response_model=DeclineWordResponse)
async def decline_new_word(
    request: DeclineWordRequest,
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session),
):
    """
    Decline a new word and recalculate preview.
    
    The declined word will be marked as ignored and won't be offered again.
    Preview is recalculated with the next word by rank.
    """
    service = LessonPreviewService(session, current_user)
    preview = await service.decline_word(request.word_id)
    
    return DeclineWordResponse(
        message="Слово успешно отклонено",
        preview=preview,
    )


@router.post("/evaluate", response_model=EvaluateResponse)
async def evaluate_exercise(
    request: EvaluateRequest,
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session),
):
    """
    Evaluate user translation for an exercise.
    
    Uses LLM to check translation accuracy and update SRS.
    """
    service = LessonExerciseService(session, current_user.id)
    return await service.evaluate_exercise(
        exercise_id=request.exercise_id,
        user_translation=request.user_translation,
        dont_know=request.dont_know or False
    )


@router.get("/{lesson_id}/exercises/{exercise_id}", response_model=ExerciseInfoResponse)
async def get_exercise_info(
    lesson_id: int,
    exercise_id: int,
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session),
):
    """
    Get exercise information.
    
    Returns exercise details including sentence and status.
    """
    service = LessonExerciseService(session, current_user.id)
    return await service.get_exercise_info(lesson_id, exercise_id)


@router.get("/{lesson_id}/exercises/{exercise_id}/result", response_model=ExerciseResultResponse)
async def get_exercise_result(
    lesson_id: int,
    exercise_id: int,
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session),
):
    """
    Get cached result for an evaluated exercise.
    
    Used to restore review screen after page reload.
    """
    service = LessonExerciseService(session, current_user.id)
    return await service.get_exercise_result(lesson_id, exercise_id)


@router.post("/exercises/{exercise_id}/suggestions/{word_id}", response_model=SuggestionActionResponse)
async def handle_suggestion(
    exercise_id: int,
    word_id: int,
    request: SuggestionActionRequest,
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session),
):
    """
    Add or ignore a suggested word.
    
    - add: Create user_word and mark suggestion as added
    - ignore: Mark suggestion as ignored
    """
    service = SuggestionService(session, current_user.id)
    return await service.handle_suggestion(exercise_id, word_id, request.action)


@router.post("/exercises/{exercise_id}/report", response_model=ReportResponse)
async def report_exercise(
    exercise_id: int,
    request: ReportRequest,
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session),
):
    """
    Report an exercise with a reason and comment.
    
    Creates or updates a report for the exercise.
    """
    service = ReportService(session, current_user.id)
    return await service.report_exercise(exercise_id, request.reason, request.comment)


@router.get("/{lesson_id}/current", response_model=CurrentExerciseResponse)
async def get_current_exercise(
    lesson_id: int,
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session),
):
    """
    Get current pending exercise for a lesson.
    
    Returns the first pending exercise with progress information.
    Raises 409 if lesson is completed or abandoned.
    """
    service = LessonResumeService(session, current_user.id)
    return await service.get_current_exercise(lesson_id)


@router.post("/{lesson_id}/abandon", response_model=AbandonResponse)
async def abandon_lesson(
    lesson_id: int,
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session),
):
    """
    Abandon a lesson.
    
    Marks lesson as abandoned. Does not return daily limit.
    Does not revert SRS changes for processed words.
    Idempotent: returns success if already abandoned.
    """
    service = LessonResumeService(session, current_user.id)
    message = await service.abandon_lesson(lesson_id)
    return AbandonResponse(message=message)


@router.get("/{lesson_id}/summary", response_model=LessonSummaryResponse)
async def get_lesson_summary(
    lesson_id: int,
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session),
):
    """
    Get lesson summary with statistics.
    
    Only available for completed lessons.
    Includes word statistics and streak information.
    """
    service = LessonSummaryService(session, current_user)
    return await service.get_summary(lesson_id)
